# ── Identificación del proyecto ──────────────────────────────
sonar.organization=gabrielgarciatoriz
sonar.projectKey=GabrielGarciaToriz_GGarciaBancoFrontend
sonar.projectName=GGarciaBancoFrontend
sonar.projectVersion=1.0

# ── Conexión a SonarCloud ─────────────────────────────────────
sonar.host.url=https://sonarcloud.io

# ── Fuentes ───────────────────────────────────────────────────
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/assets/**

# ── Cobertura de código ───────────────────────────────────────
sonar.javascript.lcov.reportPaths=coverage/GGarciaBancoFrontend/lcov.info
#sonar.testExecutionReportPaths=reports/test-report.xml

# ── Encoding ──────────────────────────────────────────────────
sonar.sourceEncoding=UTF-8